### ISSUE TITLE
Automating security baselines to achieve compliance

### ISSUE THREAD

**Issue by uk-bolly** [londoninfrastructureascode/Londoniac-meetup#1]
## Audit and Remediation of Security Baselines
provided by 

https://www.lockdownenterprise.com
https://github.com/ansible-lockdown

#### Helping to bring the dev, sec and ops together

- Running security benchmark Audit - using goss
   - Much faster than market leaders for compliance scanning
   - Easy to configure
   - Align with internal requirements
 
- Remediating a system and bring into compliance - using Ansible
   - Highly configurable
   - Ability to supply your own settings

Ability to run them both together using one configuration to audit and remediate.

### 30-45mins

https://www.linkedin.com/in/mark-bolwell-83b4915
https://www.linkedin.com/company/mindpoint-group-llc/

https://www.mindpointgroup.com

**Comment by londoninfrastructureascode** [comment]
I'd like to have you do this talk at the next meetup. I just need to work out a venue. I'll come back with dates shortly.

**Comment by londoninfrastructureascode** [comment]
I gave out the wrong link! I'll be removing this repo shortly.

Any chance you could add it here: https://github.com/londoniac/Londoniac-meetup/issues/new/choose

Sorry about that Mark.

**Comment by uk-bolly** [comment]
Hi Dennis

Will be a couple of hours before I can move to the new repo. But not a
problem at all.

Thanks

Mark

**Comment by uk-bolly** [comment]
Should be there now.

Thanks
